### ISSUE TITLE
style: Modpack specific changelogs

### ISSUE THREAD

**Issue by aninusmuffin** [ParadigmMC/mc-modpack-kit#26]
The default Changelogs generated by Release Please dont't really fit modpacks.

For example: 
- one of the most common changes in modpacks are mod updates, but there's no obvious way to mark these with Conventional commits. What type should I use for them? Most mod updates IMO don't require a minor version change since most mod updates are also patch releases. (Or maybe i just shouldn't write out all the updated mods :P )

It would be nice if there were options to customize how the changelog is generated, also I'm not really familiar with changelogs or Release Please, but i wanted to open this issue to start a discussion.

**Comment by jh-devv** [comment]
This can be addressed with editing the release please config at the `pipeline.yml`.
For my modpack, I have used the e.g. `feat(modpack): add sodium` type of commits.

**Comment by sofiedotcafe** [comment]
@Aninuscsalas If you meant mod updates, I would use `chrore(modpack): updates sodium`

**Comment by sofiedotcafe** [comment]
Maybe I'll add more to the readme for this
So it would be like:
- `chore(modpack): update <mod>` This updates a specific mod
- `feat(modpack): add <mod>` This add a specific mod
Note: When you use `chore` it does not add it to the release description because its used for e.g. changing versions

@Aninuscsalas Is this good?

**Comment by aninusmuffin** [comment]
> @Aninuscsalas Is this good?

Yeah, I think this helps people new to the project

**Comment by sofiedotcafe** [comment]
@Aninuscsalas Done in PR #34
