### ISSUE TITLE
bug: Changelogs uploaded to modrinth are empty

### ISSUE THREAD

**Issue by aninusmuffin** [ParadigmMC/mc-modpack-kit#27]
When uploading a pack to modrinth the changelog is empty and just says null

**Comment by sofiedotcafe** [comment]
Could you share the repo this is happening?

**Comment by aninusmuffin** [comment]
It's a simple nearly empty private test repo but I invited you

**Comment by sofiedotcafe** [comment]
Good! I look into this tomorrow morning, thanks for reporting this! ❤️

**Comment by sofiedotcafe** [comment]
@Aninuscsalas This seems to be because the repo is private

**Comment by jh-devv** [comment]
@Aninuscsalas Can you give me the acccess to the Modrinth page?

**Comment by aninusmuffin** [comment]
> @Aninuscsalas This seems to be because the repo is private

Yep, this was the issue thx

**Comment by sofiedotcafe** [comment]
Fixed with commit 07688f7
