### ISSUE TITLE
feat: Bug report Issue Template

### ISSUE THREAD

**Issue by aninusmuffin** [ParadigmMC/mc-modpack-kit#40]
**Is your feature request related to a problem? Please describe.**
A bug report option to the issue templates. Just wanted to report a bug but then saw that there was no bug option.

**Describe the solution you'd like**
A bug report template for easy bug reporting

**Comment by sofiedotcafe** [comment]
:+1:

**Comment by sofiedotcafe** [comment]
Added with commit: 90b37ac
