### ISSUE TITLE
Update to mc-publish v3.3.0

### ISSUE THREAD

**Issue by aninusmuffin** [ParadigmMC/mc-modpack-kit#71]
**Describe the bug**

mc-modpack-kit fails to publish

https://github.com/Aninuscsalas/wynncraft-101/actions/runs/7652140532/job/20851328526

```
Error: Unable to resolve action `Kir-Antipov/mc-publish@v3.2`, unable to find version `v3.2`
```

mc-publish v3.2.0 is deprecated, as GitHub no longer supports actions based on Node.js 12.

**Comment by sofiedotcafe** [comment]
Thanks for providing the issue for me!

Updated with commit https://github.com/jh-devv/mc-modpack-kit/commit/2772ee596fb1f3e92674217a5aa0ff6bd68dc74a
