### ISSUE TITLE
Possibly a bugged or incorrectly configured modpack forcing a publish each commit

### ISSUE THREAD

**Issue by ghost** [ParadigmMC/mc-modpack-kit#74]
**Describe the bug**
Each time a commit is made onto main, the commit itself will cause a publish to occur rather than updating a pull request. 

**Expected behavior**
It should make a pull request and not publish.

**Logs**
https://pastebin.com/zWuHUX5i

**Comment by sofiedotcafe** [comment]
This is intresting, could you share the GitHub repo by any change so I could see closer?

**Comment by ghost** [comment]
https://github.com/DannyLeWasTaken/DAM

**Comment by sofiedotcafe** [comment]
> https://github.com/DannyLeWasTaken/DAM

Could be caused by the "bit excessive" use of the bump action, release please should handle bumps by itself.

The action is mainly used for bumping from the *0.1.0* to *1.0.0*, like beta to release.

You could try to generate an new project from the template if you want, since this seems like an *release please* thing, at least I haven't seen this before.

**Comment by ghost** [comment]
Gotcha. A fix would be nice since it would be annoying to have to do this if my modpack bugs out

**Comment by aninusmuffin** [comment]
Same issue here: 

Instead of bumping the pack and creating a PR the action releases itself as the previous version again and again. 

- https://github.com/Aninuscsalas/wynncraft-101/actions/runs/8507112970/job/23298408306
- https://github.com/Aninuscsalas/wynncraft-101/actions/runs/8507071593

**Comment by sofiedotcafe** [comment]
https://stackoverflow.com/questions/75806309/release-please-creates-the-same-release-pr-after-merge Related?

**Comment by sofiedotcafe** [comment]
Hey! I found the issue: 

> If you were previously configuring advanced options via GitHub action inputs, you will need to configure via the release-please manifest configuration instead. Below, you can see a mapping of the old option to the new option:

It seems that the update from `release-please-action` `v3` to `v4` broke this, weird that the dependency bot didn't find this as an issue!

**Comment by sofiedotcafe** [comment]
This seems to be mainly the fault of GitHub actions, that's why the issue #78 was created...
