### ISSUE TITLE
Packwiz doesn't generate pack.toml/creates empty index.toml

### ISSUE THREAD

**Issue by IogaMaster** [ParadigmMC/mc-modpack-kit#75]
**Describe the bug**

It creates an *EMPTY* index.toml
Also doesn't create a pack.toml file at ALL.

**To Reproduce**
1. Create to repo from template and clone
2. use direnv
3. packwiz init
4. No file generated after use

**Comment by sofiedotcafe** [comment]
Could you share your terminal output? Packwiz should be automatically installed using nix?

**Comment by IogaMaster** [comment]
![image](https://github.com/ParadigmMC/mc-modpack-kit/assets/67164465/b7e93c95-3624-454c-a7d0-5b70ef07ef96)
![image](https://github.com/ParadigmMC/mc-modpack-kit/assets/67164465/6b5b94b7-cc33-418a-bbd2-eea180a13c8b)

**Comment by sofiedotcafe** [comment]
Maybe a Packwiz issue then? I don't really know

**Comment by IogaMaster** [comment]
I did not generate the index.toml in the `main/` dir
