### ISSUE TITLE
error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)

### ISSUE THREAD

**Issue by MimzyFang** [ParadigmMC/mc-modpack-kit#79]
**Describe the bug**
just updated my pack and ran into that error message in the Build Modpack Step
```
  error: file 'nixpkgs' was not found in the Nix search path (add it using $NIX_PATH or -I)
  
         at «none»:0: (source not available)
  Error: The process '/nix/var/nix/profiles/default/bin/nix-env' failed with exit code 1
```

**To Reproduce**
1. push to branch
2. it errors in the Handle Releases step

**Expected behavior**
it should work

**Additional context**
pipeline that errored
https://github.com/Fauli1221/PonyCraftANewGenerationVanilla/actions/runs/8480132868/job/23235321967

**Comment by sofiedotcafe** [comment]
Fixed with #80
